// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const getDatabaseUrl = () => {
  let url = process.env["DATABASE_URL"] || "";
  if (url.includes("${")) {
    url = url.replace(/\${(\w+)}/g, (_, name) => process.env[name] || "");
  }
  return url;
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: getDatabaseUrl(),
  },
});
